export const CONFIG = {
  themes: {
    dark: {
      "--vscode-bg": "#1e1e1e",
      "--vscode-text": "#d4d4d4",
      "--vscode-text-muted": "#888888",
      "--vscode-sidebar": "#252526",
      "--vscode-editor": "#1e1e1e",
      "--vscode-tab": "#2d2d2d",
      "--vscode-tab-active": "#1e1e1e",
      "--vscode-border": "#3c3c3c",
      "--vscode-hover": "#2a2d2e",
      "--vscode-accent-blue": "#569cd6",
      "--vscode-accent-green": "#4ec9b0",
      "--vscode-accent-red": "#f44747",
      "--vscode-accent-yellow": "#dcdcaa",
      "--vscode-selection": "#264f78",
    },
    light: {
      "--vscode-bg": "#ffffff",
      "--vscode-text": "#333333",
      "--vscode-text-muted": "#6c757d",
      "--vscode-sidebar": "#f3f3f3",
      "--vscode-editor": "#ffffff",
      "--vscode-tab": "#e7e7e7",
      "--vscode-tab-active": "#ffffff",
      "--vscode-border": "#d1d1d1",
      "--vscode-hover": "#e2e2e2",
      "--vscode-accent-blue": "#0066cc",
      "--vscode-accent-green": "#2e8b57",
      "--vscode-accent-red": "#cc0000",
      "--vscode-accent-yellow": "#ffcc00",
      "--vscode-selection": "#cce4ff",
    },
  },
  debounceDelay: 300,
};
